[package]
name = "rustracing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
glam = "0.29.2"
png = "0.17.16"
rand = "0.8.5"
rayon = "1.10.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
